/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiRecommendation: typeof import('./src/components/analysis/AiRecommendation.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AssetDrawer: typeof import('./src/components/common/AssetDrawer.vue')['default']
    BrandQuickFilter: typeof import('./src/components/home/BrandQuickFilter.vue')['default']
    BuyButton: typeof import('./src/components/analysis/BuyButton.vue')['default']
    CrossPlatform: typeof import('./src/components/analysis/CrossPlatform.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    MiniProgramBanner: typeof import('./src/components/common/MiniProgramBanner.vue')['default']
    PriceDisplay: typeof import('./src/components/common/PriceDisplay.vue')['default']
    PriceTrendChart: typeof import('./src/components/analysis/PriceTrendChart.vue')['default']
    PriceWaterfall: typeof import('./src/components/analysis/PriceWaterfall.vue')['default']
    ProductCard: typeof import('./src/components/home/ProductCard.vue')['default']
    ProductHeader: typeof import('./src/components/analysis/ProductHeader.vue')['default']
    RankFilters: typeof import('./src/components/rank/RankFilters.vue')['default']
    RankTable: typeof import('./src/components/rank/RankTable.vue')['default']
    RecommendGrid: typeof import('./src/components/home/RecommendGrid.vue')['default']
    RiskTags: typeof import('./src/components/analysis/RiskTags.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/home/SearchBar.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
